name: Build & Deploy API

on:
  push:
    branches:
      - main
    paths:
      - 'packages/server/**'

  workflow_dispatch:
#       inputs:
#         logLevel:
#           description: 'Log level'     
#           required: true
#           default: 'warning'
#         tags:
#           description: 'Test scenario tags'  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cake-boss-api"
          heroku_email: "sergiomos2010@gmail.com"
        env:
          HD_APP_BASE: "packages/server"
