name: Build & Deploy Web Client

on:
  push:
    branches:
      - main
    paths:
      - 'packages/server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cake-boss-web-client"
          heroku_email: "sergiomos2010@gmail.com"
        env:
          HD_APP_BASE: "package/web"
          HD_REACT_APP_API_URL: "https://cake-boss-api.herokuapp.com/"
